### ISSUE TITLE
Domain no longer functional

### ISSUE THREAD

**Issue by pbrisbin** [thoughtbot/maybe_haskell#82]
:wave: Hi thoughtbot,

https://maybe-haskell.com broke when you changed some registrar info and didn't re-verify (I guess). Is it possible to get that fixed?

I'm also happy to take over the domain myself and set up a redirect to this GitHub repo -- let me know.

**Comment by jferris** [comment]
@pbrisbin It looks like we failed a verification check with out registrar. I'm checking it out.

**Comment by cpytel** [comment]
I've fixed this. It may take a little bit for the fix to propagate to you. Sorry for the trouble, and thanks.
