### ISSUE TITLE
Incorrect type/definition for `userFromParams` in follow-the-types.md

### ISSUE THREAD

**Issue by null-calx** [thoughtbot/maybe_haskell#83]
The definitions given in `book/applicative/follow-the-types.md` are:

```haskell
fmapUser :: Maybe (String -> User)
fmapUser = User <$> getParam "name" params

aMaybeEmail :: Maybe String
aMaybeEmail = getParam "email" params
```

and finally

```haskell
userFromParams :: Params -> Maybe User
userFromParams params = fmapUser <*> aMaybeEmail
```
But following this, `userFromParams` should not be a function of `params`, I believe.

Rather a more correct definition would be:

```haskell
userFromParams :: Maybe User
userFromParams = fmapUser <*> aMaybeEmail
```

**Comment by null-calx** [comment]
That would be so cool of you, thank you!

Also, the book was an awesome read. I loved it. Thank you for writing it. :)

**Comment by pbrisbin** [comment]
Thank you very much!

I'll get that PR merged soon and then figure out how to produce updated PDFs... it's been a while :sweat_smile:
